### ISSUE TITLE
couldn't find "libandenginephysicsbox2dextension.so"

### ISSUE THREAD

**Issue by oalpayli** [nicolasgramlich/AndEnginePhysicsBox2DExtension#14]
Hi,

I use andengine and box2dextension libraries in my game. When I try my game on lg g4 with 64 bit processor, I get below error:

E/AndEngine: GameActivity.onCreateScene failed. @(Thread: 'GLThread 1447')
                                                               java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.revolvia.fivepop-1/base.apk"],nativeLibraryDirectories=[/data/app/com.revolvia.fivepop-1/lib/arm64, /vendor/lib64, /system/lib64]]] couldn't find "libandenginephysicsbox2dextension.so"
                                                                   at java.lang.Runtime.loadLibrary(Runtime.java:366)
                                                                   at java.lang.System.loadLibrary(System.java:988)
                                                                   at org.andengine.extension.physics.box2d.PhysicsWorld.<clinit>(PhysicsWorld.java:36)
                                                                   at com.revolvia.fivepop.activities.GameActivity.onCreateScene(GameActivity.java:386)
                                                                   at org.andengine.ui.activity.SimpleLayoutGameActivity.onCreateScene(SimpleLayoutGameActivity.java:48)
                                                                   at org.andengine.ui.activity.BaseGameActivity$3.onCreateResourcesFinished(BaseGameActivity.java:169)
                                                                   at org.andengine.ui.activity.SimpleLayoutGameActivity.onCreateResources(SimpleLayoutGameActivity.java:43)
                                                                   at org.andengine.ui.activity.BaseGameActivity.onCreateGame(BaseGameActivity.java:181)
                                                                   at org.andengine.ui.activity.BaseGameActivity.onSurfaceCreated(BaseGameActivity.java:110)
                                                                   at org.andengine.opengl.view.EngineRenderer.onSurfaceCreated(EngineRenderer.java:80)
                                                                   at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1500)
                                                                   at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1239)

Please Help me..

**Comment by farazappy** [comment]
Exact same error, help please.

**Comment by farazappy** [comment]
Adding `ndk {
        abiFilters "armeabi-v7a", "x86", "armeabi", "mips"
    }` under `defaultConfig{}` in app.gradle file fixes the problem, In addition add `android.useDeprecatedNdk=true` to gradle.properties.
