### ISSUE TITLE
Crash on android 6: libandenginephysicsbox2dextension.so: has text relocations

### ISSUE THREAD

**Issue by Barina** [nicolasgramlich/AndEnginePhysicsBox2DExtension#16]
There's a problem when targeting to SDK level 23
The app just crashing saying "libandenginephysicsbox2dextension.so: has text relocations"
As shown in the  attached logcat:

```
/data/app/<APP-PACKAGE>/lib/arm/libandenginephysicsbox2dextension.so: has text relocations
FATAL EXCEPTION: UpdateThread
Process: <APP-PACKAGE>, PID: 16897
Theme: themes:{default=overlay:com.blazze11.euphoria.dark, fontPkg:com.blazze11.euphoria.dark, com.android.systemui=overlay:com.blazze11.euphoria.dark, com.android.systemui.navbar=overlay:com.blazze11.euphoria.dark}
java.lang.UnsatisfiedLinkError: dlopen failed: /data/app/<APP-PACKAGE>/lib/arm/libandenginephysicsbox2dextension.so: has text relocations
at java.lang.Runtime.loadLibrary(Runtime.java:372)
at java.lang.System.loadLibrary(System.java:1076)
at org.andengine.extension.physics.box2d.PhysicsWorld.<clinit>(PhysicsWorld.java:35)
at <APP-PACKAGE>.engine.scene.GameScene.createScene(GameScene.java:148)
at <APP-PACKAGE>.engine.scene.BaseScene.<init>(BaseScene.java:31)
at <APP-PACKAGE>.engine.scene.GameScene.<init>(GameScene.java:67)
at <APP-PACKAGE>.engine.scene.SceneManager.createGameScene(SceneManager.java:77)
at <APP-PACKAGE>.engine.scene.SceneManager.setScene(SceneManager.java:38)
at <APP-PACKAGE>.engine.scene.MainMenuScene.startNewGame(MainMenuScene.java:93)
at <APP-PACKAGE>.engine.scene.MainMenuScene.onMenuItemClicked(MainMenuScene.java:72)
at org.andengine.entity.scene.menu.MenuScene.onAreaTouched(MenuScene.java:139)
at org.andengine.entity.scene.Scene.onAreaTouchEvent(Scene.java:413)
at org.andengine.entity.scene.Scene.onSceneTouchEvent(Scene.java:357)
at org.andengine.entity.scene.CameraScene.onSceneTouchEvent(CameraScene.java:64)
at org.andengine.entity.scene.Scene.onChildSceneTouchEvent(Scene.java:420)
at org.andengine.entity.scene.Scene.onSceneTouchEvent(Scene.java:338)
at org.andengine.engine.Engine.onTouchScene(Engine.java:452)
at org.andengine.engine.Engine.onTouchEvent(Engine.java:438)
at org.andengine.input.touch.controller.BaseTouchController$TouchEventRunnablePoolItem.run(BaseTouchController.java:102)
at org.andengine.util.adt.pool.RunnablePoolUpdateHandler.onHandlePoolItem(RunnablePoolUpdateHandler.java:54)
at org.andengine.util.adt.pool.RunnablePoolUpdateHandler.onHandlePoolItem(RunnablePoolUpdateHandler.java:1)
at org.andengine.util.adt.pool.PoolUpdateHandler.onUpdate(PoolUpdateHandler.java:88)
at org.andengine.input.touch.controller.BaseTouchController.onUpdate(BaseTouchController.java:62)
at org.andengine.engine.Engine.onUpdate(Engine.java:584)
at org.andengine.engine.Engine.onTickUpdate(Engine.java:548)
at org.andengine.engine.Engine$UpdateThread.run(Engine.java:820)
```

**Comment by xdung91** [comment]
You can use this jniLibs:
https://www.dropbox.com/s/k18vqm1owler15v/jniLibs.rar?dl=0

It's build for android 6.0 Marshmallow!
I got the same problem and i spend hafl day for this things.

**Comment by Barina** [comment]
Thanks a lot I'll take a look at it 
What about older API versions?

**Comment by xdung91** [comment]
It's work fine for older API. :D

**Comment by vlery** [comment]
appreciate

**Comment by jjborde** [comment]
This solution worked! Thanks. How did you created this .so file or jniLibs ?
